# Generated by Django 5.2 on 2025-05-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='quantityinstock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
