# Generated by Django 5.2 on 2025-05-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_part_quantityinstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
