# Generated by Django 5.2 on 2025-05-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_order_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='technical_specs',
            field=models.TextField(null=True),
        ),
    ]
