# Generated by Django 5.2 on 2025-05-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_part_brand_alter_part_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='type',
        ),
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
